# Generated by Django 4.2.7 on 2023-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AiApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visual",
            name="prompt",
            field=models.CharField(max_length=120),
        ),
    ]
